# GitHub'da destek seçeneklerini belirle
github: [BurhanYslmn] # GitHub Sponsor profilin için
custom: ['https://steamcommunity.com/tradeoffer/new/?partner=493377042&token=h4-_nRPP'] # Diğer yöntemler için
